### ISSUE TITLE
pass arguments and write to database

### ISSUE THREAD

**Issue by patricksebastien** [fojuth/plupload#10]
I was wondering if you could give me some advice on how to implement the following scenario:
- when uploading a file, pass an argument for the userID and the categoryID (for ie) so that it is possible to create a directory for the user and category;
- insert the information about the uploaded file in a database;

Thank you!

**Comment by fojuth** [comment]
I guess you could use a custom uploader view where you could pass initial data or set it dynamically via JS.

```
{{ plupload($custom_view_path) }}
```

In the config file (once you publish it) you can set a different upload handler:

```
'upload_handler' => '\Custom\UploadHandler'
```

In this handler you can probably fetch the userID and/or categoryID. I haven't tested this so you should check this yourself.

Alternatively you can change the gate and try to handle it there:

```
'upload_handler_gate' => \URL::to('plupload/gate')
```

Let me know if this helps.
