### ISSUE TITLE
Fix for laravel 4.2

### ISSUE THREAD

**Issue by jgoyvaerts** [fojuth/plupload#6]
can you fix this so its compatible with laravel 4.2?

**Comment by fojuth** [comment]
I'll try, but I have very little time at the moment, so I don't know when I'll be actually able to do this. If you have a solution for this package, so it will work with Laravel 4.2.\* than I'll be more than happy to include it. If not than I'll try to find some time in the upcoming days to sit down to it.

**Comment by fojuth** [comment]
Well, this has been hanging for a while. I recently created s branch for Laravel 4.2. Feel free to check it out. I must warn you though, I didn't really test it yet, that's why it's not tagged. Should you find any bugs, please drop me a line.
